### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia/typescript-types#12]
This is a reminder to release a new version of the library.
@DannyS712 is there any date we should work towards or anything you need for the next release for GlobalWatchlist ?

**Comment by DannyS712** [comment]
I'm not using typescript in GlobalWatchlist, so no specific date or feature requests

**Comment by jdlrobson** [comment]
Okay no problem. Once the other 2 patches land I'll do one.

**Comment by jdlrobson** [comment]
Done https://github.com/wikimedia/typescript-types/releases/tag/v0.2.0
