### ISSUE TITLE
Add linter to ensure MediaWiki.d.ts is always valid

### ISSUE THREAD

**Issue by DannyS712** [wikimedia/typescript-types#14]
I noticed #13 - we shouldn't need to have such fix commits because ideally there would be tests that validate the typescript for each patch. I don't know how such tests are added in github though

**Comment by jdlrobson** [comment]
Yep sounds like a good idea. We can use Travis CI for that.

**Comment by lens0021** [comment]
Have you ever considered moving this repo to [Wikimedia Gitlab](https://gitlab.wikimedia.org/explore/projects/starred)? If moved, Gitlab CI would be reasonable.

**Comment by jdlrobson** [comment]
This could be moved to Gitlab eventually, yes. However that would likely be done as part of a bigger migration of several repos.
