### ISSUE TITLE
[Question] How do I handle types of other extensions?

### ISSUE THREAD

**Issue by lens0021** [wikimedia/typescript-types#17]
Hi, If this is not a suitable place for questions, feel free to close this issue.
As a skin developer, I have called to some variables defined in extensions like below without @wikimedia/types-wikimedia.

code:
```js
/** @type {EchoApi} */ var echoApi = new mw.echo.api.EchoApi();
```

`.d.ts`:
```ts
interface EchoApi {}
interface MediaWiki {
  echo: {
    api: {
      EchoApi: {
        new (): EchoApi;
      };
    };
  };
}

declare const mw: MediaWiki;
```

And I want to replace it with the library but I don't know how to. I think I have two options:
- Adding definitions for extensions to this repository.
- Extending types-wikimedia in my own skin.

About the second option, I couldn't find the syntax to extend global `mw`. (It may be because I am not familiar with TypeScript.)
What should I do?

Regards.

**Comment by jdlrobson** [comment]
Good question. Ideally I think they'd be exported by the extension via npm, however we already had this problem with eventLog(Extension:EventLogging) and documented here so I think it would be fine to document in this repo for now https://github.com/wikimedia/typescript-types/blob/master/MediaWiki.d.ts#L79

**Comment by lens0021** [comment]
I see, thank you for answering!
